version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  threatharvester:
    build: .
    container_name: threatharvester
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  es_data:
